Calculate resistances/friction by reducing parallel/series flow segments
BrewBlox/brewblox-ui pull request #416
Opened 2019-02-24 23:07 UTC by elcojacobs

This PR overhauls the flow calculation algorithm for the process view.
Flow is now correctly calculated in all cases I think, but more tests should be written.

The new algorithm calculates flow independently for each pressure source (external inputs or pumps) and superimposes them.
It calculates the resistance for the total path by reducing series and parallel segments. With that total resistance, it can calculate the start flow. On splits, this flow is divided over the split based on each segment resistance.

There are no source of sink parts after the refactor, just parts that add pressure. Input and outputs go to special coordinate -1,-1. Whether they are input or output is only determined by the pressure and resulting flow. 
We probably merge them into a single part.

2019-02-25 11:28 UTC, steersbob requested changes

2019-02-25 11:28 UTC, steersbob commented on src/plugins/spark/features/ProcessView/calculateFlows.ts
> +  return false;
- commented code
- the logic in this function literally is `if(boolean value) { return true; } return false;`

2019-02-25 11:28 UTC, steersbob commented on src/plugins/spark/features/ProcessView/calculateFlows.ts
> -/*
You've removed a lot of documentation, without adding any for the new algorithms.

2019-02-25 11:28 UTC, steersbob commented on src/plugins/spark/features/ProcessView/calculateFlows.ts
> -        existing.liquid = combineLiquids(existing.liquid, part.liquid);
combineLiquids is unused

2019-02-25 11:28 UTC, steersbob commented on src/plugins/spark/features/ProcessView/parts/Pump.vue
> +          v-if="!part.settings.disabled"
part.settings is undefined

2019-02-25 11:28 UTC, steersbob commented on src/plugins/spark/features/ProcessView/state.d.ts
> +  settings?: Record<string, any>;
- Why is this not meaningfullly typed?
- Why is it optional? This requires anyone accessing `part.settings` to build constructs like `part.settings || {}`.

2019-02-28 12:17 UTC, steersbob approved these changes

2019-02-28 15:19 UTC, elcojacobs commented on src/plugins/spark/features/ProcessView/state.d.ts
> +  settings?: Record<string, any>;
This will be the generic place for custom settings for each part. It is generic on purpose

2019-02-28 15:20 UTC, elcojacobs commented
I think almost all issues are fixed now and this can be merged

2019-02-28 15:37 UTC, merged